'use strict';

export var GET_BLOG_POSTS = 'emprove.common.GET_BLOG_POSTS';
export var GET_POST_BY_SLUG = 'emprove.common.GET_POST_BY_SLUG';
export var DETECT_DEVICE = 'emprove.common.DETECT_DEVICE';
export var LIST_TRANSLATIONS = 'emprove.common.LIST_TRANSLATIONS';
export var RESET_SNACKBAR = 'emprove.common.RESET_SNACKBAR';
export var SET_SNACKBAR = 'emprove.common.SET_SNACKBAR';
export var SET_LANDING_VISITED = 'emprove.common.SET_LANDING_VISITED';
export var TOGGLE_DRAWER = 'emprove.common.TOGGLE_DRAWER';
export var EXPORT_RFP_PDF = 'emprove.common.EXPORT_RFP_PDF';
export var DOWNLOAD_RFP_PDF = 'emprove.common.DOWNLOAD_RFP_PDF';
export var SEND_RFP_PDF = 'emprove.common.SEND_RFP_PDF';
export var EXPORT_RFP_SUMMARY_PDF = 'emprove.common.EXPORT_RFP_SUMMARY_PDF';
export var SEND_RFP_SUMMARY_PDF = 'emprove.common.SEND_RFP_SUMMARY_PDF';
export var EXPORT_BID_PDF = 'emprove.common.EXPORT_BID_PDF';
export var DOWNLOAD_BID_PDF = 'emprove.common.DOWNLOAD_BID_PDF';
export var SEND_BID_PDF = 'emprove.common.SEND_BID_PDF';
export var EXPORT_CONTRACT_PDF = 'emprove.common.EXPORT_CONTRACT_PDF';
export var SET_GLOBAL_PROPERTY = 'emprove.common.SET_GLOBAL_PROPERTY';
export var SUBSCRIBE = 'emprove.common.SUBSCRIBE';
export var UNSUBSCRIBE = 'emprove.common.UNSUBSCRIBE';