'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SET_GLOBAL_PROPERTY = exports.EXPORT_CONTRACT_PDF = exports.SEND_BID_PDF = exports.DOWNLOAD_BID_PDF = exports.EXPORT_BID_PDF = exports.SEND_RFP_PDF = exports.DOWNLOAD_RFP_PDF = exports.EXPORT_RFP_PDF = exports.TOGGLE_DRAWER = exports.SET_LANDING_VISITED = exports.SET_SNACKBAR = exports.RESET_SNACKBAR = exports.LIST_TRANSLATIONS = exports.DETECT_DEVICE = exports.GET_POST_BY_SLUG = exports.GET_BLOG_POSTS = void 0;
var GET_BLOG_POSTS = 'emprove.common.GET_BLOG_POSTS';
exports.GET_BLOG_POSTS = GET_BLOG_POSTS;
var GET_POST_BY_SLUG = 'emprove.common.GET_POST_BY_SLUG';
exports.GET_POST_BY_SLUG = GET_POST_BY_SLUG;
var DETECT_DEVICE = 'emprove.common.DETECT_DEVICE';
exports.DETECT_DEVICE = DETECT_DEVICE;
var LIST_TRANSLATIONS = 'emprove.common.LIST_TRANSLATIONS';
exports.LIST_TRANSLATIONS = LIST_TRANSLATIONS;
var RESET_SNACKBAR = 'emprove.common.RESET_SNACKBAR';
exports.RESET_SNACKBAR = RESET_SNACKBAR;
var SET_SNACKBAR = 'emprove.common.SET_SNACKBAR';
exports.SET_SNACKBAR = SET_SNACKBAR;
var SET_LANDING_VISITED = 'emprove.common.SET_LANDING_VISITED';
exports.SET_LANDING_VISITED = SET_LANDING_VISITED;
var TOGGLE_DRAWER = 'emprove.common.TOGGLE_DRAWER';
exports.TOGGLE_DRAWER = TOGGLE_DRAWER;
var EXPORT_RFP_PDF = 'emprove.common.EXPORT_RFP_PDF';
exports.EXPORT_RFP_PDF = EXPORT_RFP_PDF;
var DOWNLOAD_RFP_PDF = 'emprove.common.DOWNLOAD_RFP_PDF';
exports.DOWNLOAD_RFP_PDF = DOWNLOAD_RFP_PDF;
var SEND_RFP_PDF = 'emprove.common.SEND_RFP_PDF';
exports.SEND_RFP_PDF = SEND_RFP_PDF;
var EXPORT_BID_PDF = 'emprove.common.EXPORT_BID_PDF';
exports.EXPORT_BID_PDF = EXPORT_BID_PDF;
var DOWNLOAD_BID_PDF = 'emprove.common.DOWNLOAD_BID_PDF';
exports.DOWNLOAD_BID_PDF = DOWNLOAD_BID_PDF;
var SEND_BID_PDF = 'emprove.common.SEND_BID_PDF';
exports.SEND_BID_PDF = SEND_BID_PDF;
var EXPORT_CONTRACT_PDF = 'emprove.common.EXPORT_CONTRACT_PDF';
exports.EXPORT_CONTRACT_PDF = EXPORT_CONTRACT_PDF;
var SET_GLOBAL_PROPERTY = 'emprove.common.SET_GLOBAL_PROPERTY';
exports.SET_GLOBAL_PROPERTY = SET_GLOBAL_PROPERTY;