version: 2
jobs:
  build:
    working_directory: ~/emprove-common
    docker:
      - image: circleci/node:10.6.0-browsers
    steps:
      - checkout

      - run:
          name: Building & Testing
          command: |
            npm install
            npm test
            npm run build

      - add_ssh_keys:
          fingerprints:
            # For GitHub to have write access
            - "59:9e:17:8b:8c:f9:6b:f5:5c:ef:72:64:47:40:4e:95"

      - run:
          name: Git Tagging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "0.0.1" ] || [ "${CIRCLE_BRANCH}" == "0.0.2" ] || [ "${CIRCLE_BRANCH}" == "0.0.3" ] || [ "${CIRCLE_BRANCH}" == "0.0.4" ] || [ "${CIRCLE_BRANCH}" == "0.0.5" ] || [ "${CIRCLE_BRANCH}" == "0.0.6" ] ||
              [ "${CIRCLE_BRANCH}" == "0.0.7" ] || [ "${CIRCLE_BRANCH}" == "0.0.8" ] || [ "${CIRCLE_BRANCH}" == "0.0.9" ] || [ "${CIRCLE_BRANCH}" == "0.0.10" ] || [ "${CIRCLE_BRANCH}" == "0.0.11" ] || [ "${CIRCLE_BRANCH}" == "0.0.12" ] || [ "${CIRCLE_BRANCH}" == "0.0.13" ] ||
              [ "${CIRCLE_BRANCH}" == "0.0.14" ] || [ "${CIRCLE_BRANCH}" == "0.0.15" ] || [ "${CIRCLE_BRANCH}" == "0.0.16" ] || [ "${CIRCLE_BRANCH}" == "0.0.17" ] || [ "${CIRCLE_BRANCH}" == "0.0.18" ] || [ "${CIRCLE_BRANCH}" == "0.0.19" ]; then
              git fetch --tags
              git tag ${CIRCLE_BRANCH}-`date +%F_%H-%M-%S`
              git push origin --tags
            else
              echo "No need to git-tag"
            fi
