'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UserLevel2 = exports.HomeArea = exports.RfpStatus = exports.ScopeAction = exports.UserAction = void 0;
var UserAction = Object.freeze({
  KEEP_EXISTING: 1,
  REMOVE: 2,
  REPAINT_ONLY: 3,
  REPLACE: 4,
  NEW: 5,
  NEW_AND_RELOCATE: 6,
  NOT_APPLICABLE: 7
});
exports.UserAction = UserAction;
var ScopeAction = {
  NEW: 1,
  REPAINT: 2,
  REMOVE: 3
};
exports.ScopeAction = ScopeAction;
var RfpStatus = {
  RFP_BEING_PREPARED: 1,
  RFP_SENT: 2,
  CONTRACTORS_CONFIRM_INTEREST: 3,
  CONTRACTORS_SUBMIT_INIT_BIDS: 4,
  CONSUMER_REVIEWS_BIDS: 5,
  CONTRACTORS_SITE_VISIT: 6,
  CONTRACTORS_SUBMIT_FINAL_BIDS: 7,
  CONSUMER_REVIEWS_FINAL_BIDS: 8,
  CONTRACTOR_GETS_AWARD: 9,
  CONSUMER_SIGNS_CONTRACT: 10,
  CONTRACTOR_SIGNS_CONTRACT: 11,
  PROJECT_STARTS: 12,
  CONSUMER_DID_NOT_RECEIVE_INIT_BIDS: 13,
  CONSUMER_DID_NOT_RECEIVE_FINAL_BIDS: 14,
  CONSUMER_DID_NOT_AWARD_CONTRACTOR: 15
};
exports.RfpStatus = RfpStatus;
var HomeArea = {
  BACKYARD: 3,
  GUEST_BATHROOM: 6,
  MASTER_BATHROOM: 8,
  POWDER_ROOM: 9,
  GUEST_BEDROOM: 10,
  MASTER_BEDROOM: 11,
  DECK: 15,
  DEN: 16,
  FOYER: 21,
  KITCHEN: 27,
  KITCHENETTE: 28,
  LIVING_ROOM: 31,
  LOFT: 32,
  OFFICE: 35,
  PATIO: 37,
  GENERAL_LIVING: 43
};
exports.HomeArea = HomeArea;
var UserLevel2 = {
  FLOOR_CONSTRUCTION: 2000,
  EXTERIOR_WALLS: 2005,
  ROOF: 2010,
  INTERIOR_WALL_CONSTRUCTION: 2015,
  INTERIOR_CEILING_CONSTRUCTION: 2020,
  FLOORING: 2025,
  WALL_FINISHES: 2030,
  CEILING_FINISHES: 2035,
  EXTERIOR_DOORS_AND_WINDOWS: 2040,
  INTERIOR_DOORS_AND_HARDWARE: 2045,
  WALL_BASE_TRIM: 2050,
  MOLDINGS: 2055,
  RAILINGS: 2060,
  CABINETS: 2065,
  CASEWORK: 2070,
  SHELVING: 2075,
  VANITIES: 2080,
  COUNTERTOPS: 2085,
  WINDOW_TREATMENTS: 2090,
  BATH_ACCESSORIES: 2095,
  KITCHEN_APPLIANCES: 2100,
  FIREPLACES: 2105,
  POOLS_AND_WATER_FEATURES: 2110,
  PLUMBING_FIXTURES: 2115,
  LIGHTING: 2120,
  DEVICES_AND_TRIMS: 2125,
  PLUMBING_PIPING: 2130,
  ELECTRICAL_WIRING: 2135,
  COMMUNICATIONS_CABLING: 2140,
  MECHANICAL_PIPING: 2145,
  MECHANICAL_DUCTING: 2150,
  EQUIPMENT: 2155,
  LANDSCAPING: 2160,
  EXTERIOR_PAVING: 2165
};
exports.UserLevel2 = UserLevel2;